keycloak:
  realm: Biobank
  auth-server-url: http://localhost:8180/auth
  resource: shipment
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-shipment]
      securityCollections:
        - name: Shipment private API's
          patterns: ['/shipment/*']

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
      url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: administrator
      initialization-mode: always

server:
  port: 9091

app:
  sampleService: http://${SAMPLE_HOST}:9092
  biobankService: http://${BIOBANK_HOST}:9093