keycloak:
  realm: Biobank
  auth-server-url: http://${KEYCLOAK_HOST}:8180/auth
  resource: shipment
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-shipment]
      securityCollections:
        - name: Shipment private API's
          patterns: ['/shipment/*']

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
      url: jdbc:mysql://${MYSQL_HOST}:3306/shipment_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: admin
      password: admin
      initialization-mode: always

server:
  port: 9091

app:
  sampleService: http://${SAMPLE_HOST}:9092
  biobankService: http://${BIOBANK_HOST}:9093